name: Run Tests on Push

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the workflow for

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Adjust to your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python test_debian_markdown.py
