name: Python Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Adjust the Python version as needed

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt  # Make sure you have a requirements.txt file

    - name: Run unit tests
      run: python -m unittest test_debian_markdown.py  # Adjust the test file name as needed
